### ISSUE TITLE
Field 'salt' doesn't have a default value

### ISSUE THREAD

**Issue by misaka00251** [Eggbertx/gochan#18]
When adding a new user.

```
Error 1364: Field 'salt' doesn't have a default value
```

Also, why is it just using three bytes?
https://github.com/Eggbertx/gochan/blob/d4b7185ecd4adcd7e177c277ff4f1c7618e7e79f/src/util.go#L285-L291

**Comment by onekopaka** [comment]
`generateSalt()` is not used in password hashing, I believe the salt field is really a leftover from thinking about password hashing, and making sure to use salting. However bcrypt generates the salt itself. 

`generateSalt()` is used for making the cookie for a session.

https://github.com/Eggbertx/gochan/blob/d4b7185ecd4adcd7e177c277ff4f1c7618e7e79f/src/manage.go#L476-L480

It may be the case that the salt field on staff table should be removed, since it's not used as far as I know.

**Comment by Eggbertx** [comment]
Like @onekopaka said, the salt field is a carryover from Kusaba X's (less than great) design and has never actually been used, so I'm going to get rid of it. I'm also going to move `config.RandomSeed` to the `DBPREFIXinfo` SQL table and its value will be randomly generated. If the `DBPREFIXinfo` table has a version row but no randomseed row, gochan will assume that something has gone catastrophically wrong, print a critical message, and exit, since this shouldn't be an issue under normal circumstances.

**Comment by Eggbertx** [comment]
On second thought, I'm going to keep `config.RandomSeed` in the JSON file, but a random one will be generated on the first run if it's an empty string.
