### ISSUE TITLE
just board

### ISSUE THREAD

**Issue by misaka00251** [Eggbertx/gochan#19]
Can't modify or delete the board. Maybe related to this?

```
Error: 404 Not Found from 127.0.0.1 @ /javascript/manage.js
```

Also, when you specify a user in a service file then run this, board can not be created. Assme the directory name is `a`.

```
ERROR: directory //home/wwwroot/b/html/a/ already exists!
```

This is my service file:

```
[Unit]
Description=gochan Daemon
After=network.target

[Service]
WorkingDirectory=/home/wwwroot/b
ExecStart=/home/wwwroot/b/gochan
User=username
Restart=always

[Install]
WantedBy=multi-user.target
```

Already `chmod -R username` the whole gochan folder for this user.

**Comment by Eggbertx** [comment]
manage.js was relatively recently merged into gochan.js, but it looks like I've neglected to reflect that in some of the templates. I thought I got all of them...
Did .../b/html/a/ already exist when you got that error? I also might make it so that if a board directory already exists, it shows a warning but doesn't give an error.

**Comment by misaka00251** [comment]
Yes, assume I create a board titled `test`, and the directory name is `t`.

When I pressed the submit button, it creates the folder `t`, and then show the error `directory already exists!`. Running with `User=root` will solve this problem.

**Comment by Eggbertx** [comment]
If making gochan run as root fixes the issue, then the issue might be that I've been lazy about error checking. Like simply checking `if err == nil` instead of checking if it equals a permissions error, a read-only directory error, etc in addition to nil.
