### ISSUE TITLE
Future of this project.

### ISSUE THREAD

**Issue by Chebyrash** [Eggbertx/gochan#5]
I was wondering if you guys are planning to further develop this project. 

I wanted to propose we change our HTTP server to a [faster one,](https://github.com/valyala/fasthttp) use Docker & Kubernetes for development / production and think about shifting media files to cloud storage like a CDN or S3.

In my opinion we should start developing a REST API which would allow us to separate that HTML and Go backend code.

A lot of your SQL code is vulnerable to SQL injection attacks. Using parameterized queries is more secure than embedding the parameters right into the query. This also allows for quicker SQL queries as the request only has to be compiled once and can be reused.

**Comment by onekopaka** [comment]
Yes, there is still much development to be done, but this has been a hobby project for the past few years, and is not always our number one focus.

In my idea of production (basically, the demo site) the built-in HTTP server only handles posting and management operations, while a separate HTTP server (such as nginx, litespeed, even IIS works) handles serving pages and images, because those HTTP servers are already well developed and tuned for that. Current instances of Gochan certainly haven't seen anywhere near the kind of traffic levels where net/http is a problem anyways. Maybe in the future, if net/http's server is really a huge portion of request times, it could be swapped out, but since it's not a problem now, I don't see a reason to potentially break it.

On the topic of containers, there is not going to be a time that I'd personally find containerization tools anywhere near attractive for either production or development. Additionally, there's already configuration for Vagrant if someone does find containerization helpful, 

S3 and other blob storage products or CDNs tend to be high cost, and historically @Eggbertx and I have hosted image boards at as low cost as possible, so almost certainly local storage would remain the default, and in the distant future there **might** be an option to automatically upload to external storage offerings. As far as I know, the image boards interested in using Gochan do not currently use anything more complicated than Cloudflare, which works perfectly fine with the current image upload system, while giving many of the CDN-like advantages.

Currently @Eggbertx has work in progress on cleaning up the management interface to use templates rather than having HTML strings embedded, and perhaps management could be moved to a formal API in the future. However, posting will almost certainly remain as is, as the current interface remains usable without JavaScript, and in even the most archaic browsers.

There certainly could be injection vulnerabilities (just taking a quick look I found a few problematic parts in the management interface), and fortunately prepared statements seem rather easy to implement with Go's database library.

These are just my thoughts however, and aren't necessarily the definitive plan.
